[package]
name = "index-ext"
version = "0.0.1"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
edition = "2018"

[dependencies]

[features]
# Activate some additional operations that require nightly
nightly = []
